module.exports = {
    USERS_PROFILE: 'users_profile',
    DEVICE: 'device',
    FRIENDS: 'friends',
    GAME_PROFILE: 'game_profile',
    SMASHES: 'smashes',
    USERS_SMASHES: 'users_smashes',
    ACHIEVEMENTS: 'achievements',
    USERS_ACHIEVEMENTS: 'users_achievements',
    COUNTRIES: 'countries',
    LANGUAGE: 'language',
    KIOSK: 'purchases',
    USERS_PURCHASES: 'users_purchases',
    NOTIFICATIONS_QUEUE: 'notifications',
    NOTIFICATIONS_HISTORY: 'notifications_history',
    GAMES_QUEUE:'game_queue',
    PURCHASE_HISTORY: 'purchase_history',
    BOOSTERS: 'boosters',
    USERS_BOOSTERS: 'users_boosters',
    FB_NOTIFICATIONS: 'fb_notifications',
    FB_NOTIFICATIONS_VIEW: 'list_fb_notif',
    PUSH_QUEUE: 'pushQueue',
    INVITES: 'invites'
};